### ISSUE TITLE
Doesn't respect proxy envvars

### ISSUE THREAD

**Issue by yardenac** [thefinn93/signal-weechat#12]
It should respect environment variables for proxy_http and so on. Or at least offer a proxy option.

**Comment by thefinn93** [comment]
Thanks for reporting this. I'm probably not going to deal with it for a while. I'm building [signald](https://github.com/thefinn93/signald) because signal-cli is a PITA to interface with, particular on a headless machine. When I get signald to a point that I'm happy with I'll get signal-weechat using it. I'll see if I can get proxy support in signald.

**Comment by tych0** [comment]
I'm gonna close this since we're on the signald branch.
