### ISSUE TITLE
Requires $DISPLAY

### ISSUE THREAD

**Issue by atoponce** [thefinn93/signal-weechat#13]
It appears that `python-dbus` prevents me from executing this while running Weechat on a headless SSH server behind `tmux(1)` or `screen(1)`.

    python: stdout/stderr (signal): Traceback (most recent call last):
    python: stdout/stderr (signal):   File "/home/aaron/.weechat/python/signal.py", line 115, in send
    python: stdout/stderr (signal):     getSignal().sendMessage(message, dbus.Array(signature="s"), number)
    python: stdout/stderr (signal):   File "/home/aaron/.weechat/python/signal.py", line 104, in getSignal
    python: stdout/stderr (signal):     bus = dbus.SessionBus()
    python: stdout/stderr (signal):   File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    python: stdout/stderr (signal):     mainloop=mainloop)
    python: stdout/stderr (signal):   File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    python: stdout/stderr (signal):     bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
    python: stdout/stderr (signal):   File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    python: stdout/stderr (signal):     bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
    python: stdout/stderr (signal): dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
    =!= python: error in function "send"

**Comment by thefinn93** [comment]
This is a component of a larger problem, namely dbus. I'm hoping to replace signal-cli (which communicates via dbus) with signald (which I built because of basically this issue and communicates via unix sockets).

**Comment by Limero** [comment]
signald seems to be pretty complete by now, is there any plans to update signal-weechat with support for it?

**Comment by thefinn93** [comment]
There is preliminary support in the `signald` branch, although I believe it's missing several important features like registering.

if you do try it out, please let me know how it goes

**Comment by ersinakinci** [comment]
For anyone else reading this, there are two root problems.

### Missing bus address

The first is that when the DBus daemon launches, it assigns an address to the bus. Anything that wants to communicate with the bus needs to know its address. The Python wrapper package that `signal-weechat` relies on assumes that you're running X11, which would set the `DISPLAY` env var and provide a way of finding the address. Without `DISPLAY`, the wrapper lib chokes.

Fortunately, there's a way around this. You can explicitly set the bus address through the environment variable `DBUS_SESSION_BUS_ADDRESS`. The address is set when you launch the DBus daemon using the `--address` option.

### Session bus

You may be asking, how do you find the bus address in order to set `DBUS_SESSION_BUS_ADDRESS`? Before we answer this question, you need to understand the second root problem, which has to do with session vs. system buses.

If your system is launching the DBus daemon through systemd (e.g., Debian, Ubuntu), it was probably launched with a command that looks something like this: `/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation`. (You can confirm with `ps aux | grep dbus`.)

The address is set to `systemd:`--more on that in a moment. But notice the `--system` flag. This tells the daemon to launch a system-wide bus rather than a session bus. The problem with this behavior is that `signal-weechat` expects that you're running DBus as a session bus. So even if you had a valid address for the system bus, it wouldn't do you much good because the code is hardwired to look for a session bus.

### Workaround

A permanent fix to this bug would be to move away from DBus, as @thefinn93 has suggested; or to try using the system bus first and gracefully degrade to attempting access to a session bus, and finally display a more helpful error message if that fails.

Until then, you can work around this bug by launching the DBus daemon as a session bus and setting the `DBUS_SESSION_BUS_ADDRESS` environment variable to the bus address. In Debian and Ubuntu, you can simply do this by running `apt-get install dbus-user-session` and rebooting, which will add the appropriate configuration files to systemd to launch a DBus daemon as a per-user service and set the `DBUS_SESSION_BUS_ADDRESS` automatically as appropriate.

**Comment by ersinakinci** [comment]
I've added a helpful error message in https://github.com/thefinn93/signal-weechat/pull/17. That PR also allows users to switch between using the session or system bus with `/set var.plugins.python.signal.bus [system, session]`. The option actually existed before but wasn't respected.

We may want to close this issue because it's not fundamentally a bug, it occurs when the operating environment isn't properly set up to work with DBus. The new error message should go some way to explain what to do in that event.

**Comment by tych0** [comment]
I'm gonna close this since we've moved to the signald branch.
